[package]
name = "i2c_parser"
version = "0.1.5"
authors = ["James Munns <james.munns@gmail.com>"]
description = "I2C Parser based on pigpio's I2C Sniffer Example"
license = "MIT"
repository = "https://github.com/jamesmunns/pigpio-i2c-rs"

[dependencies]
tokio-core = "0.1"
futures = "0.1"
